learning:
  step_size: 0.5
  batch_size: 600
  num_iters: 500
  decay_rate: 0.999
data:
  num_samples: 800
  noise_stddev: 0.1
mlp:
  num_hidden_layers: 4
  hidden_layer_width: 30
conv:
  layer_depths: 16
  layer_kernel_sizes: 3
display:
  refresh_rate: 10