# learning:
#   step_size: 0.05
#   batch_size: 128
#   num_iters: 500
#   decay_rate: 0.999
# data:
#   num_samples: 1024
#   noise_stddev: 0.1
# display:
#   refresh_rate: 10

learning:
  step_size: 0.3
  batch_size: 200
  num_iters: 200
  decay_rate: 0.999
data:
  num_samples: 500
  noise_stddev: 0.1
display:
  refresh_rate: 10