# TRAINING CONFIG ##
learning:
  step_size: 0.05
  batch_size: 300
  num_iters: 6000
  decay_rate: 0.999
data:
  num_samples: 800
  noise_stddev: 0.1
mlp:
  num_hidden_layers: 80
  hidden_layer_width: 100
conv:
  layer_depths: 200
  layer_kernel_sizes: 3
  num_conv_layers: 8
display:
  refresh_rate: 5

# ## 
# learning:
#   step_size: 0.09
#   batch_size: 1000
#   num_iters: 2000
#   decay_rate: 0.999
# data:
#   num_samples: 800
#   noise_stddev: 0.1
# mlp:
#   num_hidden_layers: 4
#   hidden_layer_width: 30
# conv:
#   layer_depths: 32
#   layer_kernel_sizes: 3
#   num_conv_layers: 8
# display:
#   refresh_rate: 10