learning:
  step_size: 0.1
  batch_size: 130
  num_iters: 500
  decay_rate: 0.999
data:
  num_samples: 50
  noise_stddev: 0.1
mlp:
  num_hidden_layers: 5
  hidden_layer_width: 10
display:
  refresh_rate: 10